amp: true
batch_size_per_gpu: 32
channels_last: true
clip_grad: 3.0
clip_mode: norm
cooldown_epochs: 3
data_dir: ./
dataset: Flowers102
epochs: 100
local_crops_number: 6
log_wandb: true
lr: 0.001
min_lr: 1.0e-06
model: vit_base_patch16_224
momentum_teacher: 0.9998
norm_last_layer: true
num_classes: 0
opt: lookahead_sgd
out_dim: 2048
pin_mem: true
pretrained: false
sched: cosine
teacher_temp: 0.04
warmup_epochs: 10
warmup_lr: 0
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
weight_decay: 0.0
