amp: true
apply_masking: true
batch_size_per_gpu: 32
channels_last: true
clip_grad: 3.0
clip_mode: norm
cooldown_epochs: 3
data_dir: ./
dataset: Flowers102
epochs: 100
experiments_group: '36'
local_crops_number: 6
log_wandb: true
lr: 0.0005
min_lr: 1.0e-06
model: vit_base_patch16_224
momentum_teacher: 0.9998
norm_last_layer: true
num_classes: 102
opt: lookahead_adamw
out_dim: 1024
pin_mem: true
pretrained: false
rep_w: 1
rot_prob: 0.5
rot_w: 1
sched: cosine
sl_smoothing: null
sl_w: 2.5
teacher_temp: 0.06
use_rot_loss: true
use_sl_loss: true
warmup_epochs: 10
warmup_lr: 1.0e-08
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
weight_decay: 0.04
