model: vit_base_patch16_224
pretrained: true
amp: false

dataset: test
num_classes: 10
epochs: 2
cooldown_epochs: 1

sched: cosine
smoothing: 0

opt: sgd
momentum: 0.9
weight_decay: 0
drop: 0.1
warmup_epochs: 1
warmup_lr: 0.000001
lr: 0.003

batch_size: 64
workers: 8
pin_mem: true
channels_last: true

log_wandb: false