model: vit_base_patch16_224
pretrained: false
amp: true
experiments_group: test_ssl

momentum_teacher: 0.9998
out_dim: 2048
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
local_crops_number: 6
# masked_crop_scale: [0.2, 0.6]

batch_size_per_gpu: 32
channels_last: true
pin_mem: true
norm_last_layer: true

sched: cosine
lr: 0.000625
min_lr: 0.000001
warmup_lr: 0.00000001
opt: lookahead_adamw
clip_mode: norm
clip_grad: 3.0
weight_decay: 0.04

epochs: 100
warmup_epochs: 10
cooldown_epochs: 3

dataset: Flowers102
num_classes: 102
data_dir: ./

log_wandb: false


use_sl_loss: true
use_rot_loss: true
rep_w: 1
sl_w: 1
rot_w: 1
rot_prob: 0.5
