model: vit_base_patch16_224
pretrained: false
amp: true

momentum_teacher: 0.9998
out_dim: 2048
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 0

batch_size_per_gpu: 16
channels_last: true
pin_mem: true
norm_last_layer: true

sched: cosine
lr: 0.0005
min_lr: 0.000001
warmup_lr: 0.001
opt: lookahead_adamw
clip_mode: norm
clip_grad: 3.0

epochs: 100
warmup_epochs: 10
cooldown_epochs: 3

dataset: Flowers102
num_classes: 0
data_dir: ../

log_wandb: true
